#! /bin/bash
reldir=`dirname $0`
cd $reldir/build
export ANT_HOME=util/ant
if [ -z "$1" ]; then
echo "railobuild control script"
OPTIONS="build build.and.test help list-targets update exit"
select opt in $OPTIONS; do
if [ "$opt" = "build" ]; then
	/bin/sh util/ant/bin/ant -f build.xml build
	exit
elif [ "$opt" = "build.and.test" ]; then
	/bin/sh util/ant/bin/ant -f build.xml build.and.test
	exit
elif [ "$opt" = "help" ]; then
	echo "usage (skips this prompt): railobuild [build|test|{target}]"
elif [ "$opt" = "list-targets" ]; then
	/bin/sh util/ant/bin/ant -f build.xml help
elif [ "$opt" = "update" ]; then
	/bin/sh util/ant/bin/ant -f build.xml project.update
elif [ "$opt" = "exit" ]; then
	exit
else
	#clear
	echo bad option
fi
done
fi
target=$1
parameters=""
shift
for var in "$@"
do
    parameters="$parameters -D$var"
    if [ ${var:0:15} = "build.java.home" ]; then
    JAVA_HOME=${var:16}
    echo JAVA HOME OVERRIDE! $JAVA_HOME
    export JAVA_HOME
    fi
done
/bin/sh util/ant/bin/ant -f build.xml $target -Dbasedir=. $parameters
	
			